### PR TITLE
Added An automated mailing app

### PR DESCRIPTION
**Pull request by bvks2020sameer**
Mailer is an automated mailing app to read mails from a csv file and send mails. It also has an inbuilt database storage with ability to change users. It has an interactive tkinter gui

### CODE REVIEW

**Comment by InvisiblePro** [comment]
@Idhant-6 and @MrB141107, I would request you both to test this project and provide your reviews.

**Review by Blazier07 — APPROVED** [review]
@bvks2020sameer Amazing work broo...!

**Comment by bvks2020sameer** [comment]
Thankyou

**Comment by bvks2020sameer** [comment]
Hi, Could you please add the hacktoberfest label so that it can be counted

**Pull request merged**
