### PR TITLE
Added Improved_Password_Generator.py

### PR DESCRIPTION
**Pull request by ghost**
Improved Password Generator

### CODE REVIEW

**Comment by RathodBhavya** [comment]
> Improved Password Generator

@yash-gulatii, add your code...

**Comment by ghost** [comment]
Already Added

**Comment by RathodBhavya** [comment]
@yash-gulatii, I tried adding some of my files to your repository, but I was unable to do that, although I signed in with a Git account. Can you suggest some other way to make pr/mr?
Screenshot 2023-10-01 180501

**Comment by ghost** [comment]
Try forking the repository.

**Pull request merged**
