### PR TITLE
Added Credit card fraud detection script

### PR DESCRIPTION
**Pull request by bvks2020sameer**
Credit card fraud detection dataset is considered to be the hello world of machine learning programming . The above model uses logistic regression model to predict and clssify a transaction as fraud or not .  kaggle database : <https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud>

### CODE REVIEW

**Comment by RathodBhavya** [comment]
@bvks2020sameer Don't forget to star ✨️ the repo.

**Comment by bvks2020sameer** [comment]
> @bvks2020sameer Don't forget to star ✨️ the repo.

Already starred 😄😄

**Comment by RathodBhavya** [comment]
Great...✨️✨️ @bvks2020sameer

**Comment by bvks2020sameer** [comment]
Thankyou

**Comment by RathodBhavya** [comment]
> Thankyou

Most welcome✨️✨️

**Pull request merged**
