### PR TITLE
feat: Create a Python Speed Test Typing Game

### PR DESCRIPTION
**Pull request by purnasth**
# Pull Request: Add Python Typing Game

Closes issue #71  

## PR descriptions 
I have created the Python Typing Game as per the specifications mentioned in issue #71. The game is functional, allowing users to practice and improve their typing skills. It is built using Python and provides an interactive typing experience.

## Screenshots
Screenshot 2023-10-26 161013

### CODE REVIEW

**Review by Blazier07 — APPROVED** [review]
Great work! @purnasth

**Comment by purnasth** [comment]
Thanks for merging the PR faster.

**Comment by RathodBhavya** [comment]
@purnasth, I request you make a module requirement file for your program's users.

**Comment by RathodBhavya** [comment]
> Thanks for merging the PR faster.

@purnasth, I you are happy with your response, then don't forget to star ⭐ the repo and follow for more updates.

**Comment by purnasth** [comment]
> @purnasth, I request you make a module requirement file for your program's users.

I am a beginner to the open-source community. Could you please elaborate on what this means?

**Comment by RathodBhavya** [comment]
@purnasth, I mean to say that, make a `requirement.txt` file, containing the name of the modules used in your program to make the user aware to install the following modules before running your program to avoid errors.

**Comment by purnasth** [comment]
Is it good if I create a README.md file inside this folder that contains information about my project and its requirements?

**Comment by RathodBhavya** [comment]
Sure, no problem go ahead!

**Comment by purnasth** [comment]
> Sure, no problem go ahead!

Sorry about that; I planned to include this contribution in the same PR, but the new PR was created to include the README.md.

**Pull request merged**
