### PR TITLE
Python password generator

### PR DESCRIPTION
**Pull request by DarkRaiderCB**
Please merge. Generates passwords with high degree of unpredictability. Thanks. @MrB141107

### CODE REVIEW

**Comment by RathodBhavya** [comment]
@DarkRaiderCB, may I know the reason of closing this pr.?

**Comment by DarkRaiderCB** [comment]
Actually two entirely different things went into the same PR. Also title
was password generator and hangman was also in there.
Sorry I am new to github and don't know much things so to keep things
simple i closed it and made these two new ones. Thanks for merging. Already
starred the repo.

**Comment by RathodBhavya** [comment]
@DarkRaiderCB, No worries, you'll be use to it after a while...this happens during the staring days...even I have experienced the same 😄

**Comment by DarkRaiderCB** [comment]
Thanks a lot for understanding and appreciating my submissions. 🙂🙏

**Pull request closed without merging**
