### PR TITLE
python program for DFS search on undirected graphs

### PR DESCRIPTION
**Pull request by Parthiv93**
Python program for performing DFS in Undirected graphs.
DFS (Depth-First Search) is a graph traversal algorithm used to explore and analyze undirected graphs. It starts at a source node, explores as far as possible along one branch, backtracks when necessary, and continues until all nodes are visited or a specific condition is met. DFS is used in this program to traverse an undirected graph represented by an adjacency list and find a path starting from node 'A'.

### CODE REVIEW

**Review by InvisiblePro — COMMENTED** [review]
Elaborate it...

**Comment by RathodBhavya** [comment]
@Parthiv93, explain the use of DFS and the working process.

**Comment by Parthiv93** [comment]
> Elaborate it...

Python program for performing DFS in Undirected graphs.
DFS (Depth-First Search) is a graph traversal algorithm used to explore and analyze undirected graphs. It starts at a source node, explores as far as possible along one branch, backtracks when necessary, and continues until all nodes are visited or a specific condition is met. DFS is used in this program to traverse an undirected graph represented by an adjacency list and find a path starting from node 'A'.

**Review by Blazier07 — APPROVED** [review]
Useful Algorithm!

**Pull request merged**
