### PR TITLE
Done Fixing Earlier Issues.

### PR DESCRIPTION
**Pull request by Aditya-y9**
@MrB141107 
I have done fixing Earlier Issues.
I still any problem exists, feel free to bring it to my notice.
Thanks and Regards,
Aditya Yedurkar

### CODE REVIEW

**Comment by Aditya-y9** [comment]
Also, I have deleted image files which accidently went to main.
Thanks!

**Review by Blazier07 — APPROVED** [review]
@Aditya-y9, Great work buddy...✨

**Comment by RathodBhavya** [comment]
I truly appreciate your skills, if you like the repo or are happy with my response, don't forget to ⭐ the repo and follow me for more updates.

**Comment by Aditya-y9** [comment]
Thanks Buddy!🌟

**Comment by RathodBhavya** [comment]
@Aditya-y9, Hey buddy... are you interested in an open-source contribution? Then I suggest you visit [SneakyShadows](https://github.com/SneakyShadows) once for sure

**Pull request merged**
