### PR TITLE
 Added snake game using pygame.

### PR DESCRIPTION
**Pull request by Ninja-06**
Hi @MrB141107, i would like to add  this  scripts that contains a simple snake game which is build using pygame module to this repo under hacktoberfest.

### CODE REVIEW

**Review by InvisiblePro — DISMISSED** [review]

**Review by Blazier07 — CHANGES_REQUESTED** [review]
@Ninja-06, I would like to request you add a requirements file for all the packages used.

**Comment by RathodBhavya** [comment]
@Ninja-06, I'm unable to import `constants` package...

**Comment by RathodBhavya** [comment]
> Hi @MrB141107, i would like to add this scripts that contains a simple snake game which is build using pygame module to this repo under hacktoberfest.

@Ninja-06, Once I am satisfied with you program without any bugs and errors, then your pr will surely be approved for the hacktoberfest

**Comment by Ninja-06** [comment]
> @Ninja-06, I'm unable to import `constants` package...

@MrB141107  constants is python file created to store constants in the code. which is inside folder snake_game.

**Review by Blazier07 — APPROVED** [review]
Great work! @Ninja-06

**Comment by RathodBhavya** [comment]
@Ninja-06, Don't forget to ⭐star the repo and follow me for new updates!

**Comment by Ninja-06** [comment]
> Great work! @Ninja-06

Thank you !

**Pull request merged**
