### PR TITLE
added the Pong game in python

### PR DESCRIPTION
**Pull request by 4hund3rbird**

### CODE REVIEW

**Review by Blazier07 — CHANGES_REQUESTED** [review]
@4hund3rbird, I request you to increase the speed of the paddle in `pong_game.py` and also add the "img.gif" for the `etch-a-sketch-game.py`. And also make 2 pull requests for 2 different files...

**Comment by RathodBhavya** [comment]
@4hund3rbird, don't forget to provide a description for both of the files...

**Review by InvisiblePro — CHANGES_REQUESTED** [review]
Please update the changes suggested

**Comment by 4hund3rbird** [comment]
ok I will do so.

**Pull request closed without merging**
