### PR TITLE
Create Currency Converter

### PR DESCRIPTION
**Pull request by Jishnu2608**

### CODE REVIEW

**Review by InvisiblePro — APPROVED** [review]
Hey buddy! @Jishnu2608 Your program is working very fine and smoothly, i appreciate it, but with program files, in the comments please provide a details of the program in an elaborated manner. That would be more appreciable

**Comment by Jishnu2608** [comment]
Yeah sure. I can do that

**Comment by InvisiblePro** [comment]
Yeah! Nice being collaborating with you ✨

**Comment by Jishnu2608** [comment]
@InvisiblePro , I cannot edit the code right now, so when it gets merged I will add the necessary comments.

**Comment by InvisiblePro** [comment]
Sure, that would also be fine!

**Comment by Jishnu2608** [comment]
Hey @InvisiblePro , I have added necessary comments in my earlier merged projects and raised the PRs. Kindly review and let me know for any changes. When this project gets merged, I will raise another PR with the comments within the code.

**Pull request merged**
